services:
  email-service:
    build: .
    networks:
      - shared-network
      - emaildb-network
    ports:
      - "6005:6005"
    container_name: email-service
    depends_on:
      - email-db
      - maildev
      - email-kafka
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_GROUP_ID}
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      - SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER=${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER}
      - SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER=${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER}
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_DESERIALIZER_VALUE_DELEGATE_CLASS=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_DESERIALIZER_VALUE_DELEGATE_CLASS}
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES}
      - SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE=${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY} # Integration line: Auth
      - SERVICE_SECRET_EMAIL=${SERVICE_SECRET_EMAIL} # Integration line: Auth
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6005/api/email/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
  email-db:
    image: 'postgres:13.1-alpine'
    container_name: email-db
    restart: unless-stopped
    volumes:
      - email-db-volume:/var/lib/postgresql/data
    networks:
      - emaildb-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  maildev:
    image: 'maildev/maildev'
    container_name: maildev
    networks:
      - shared-network
    ports:
      - "1080:1080"
      - "1025:1025"
  email-zookeeper:
    image: 'confluentinc/cp-zookeeper:7.6.0'
    container_name: email-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    networks:
      - shared-network
    ports:
      - "2181:2181"
  email-kafka:
    image: 'confluentinc/cp-kafka:7.6.0'
    container_name: email-kafka
    depends_on:
      - email-zookeeper
    networks:
      - shared-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
networks:
  emaildb-network:
    external: true
  shared-network:
    external: true
volumes:
  email-db-volume: